# From fiddler trace of app installation
GET https://www.phraseexpress.com/update16.php?license=DEMO&hs=43f755f83538369dd7668077bee7448b HTTP/1.1

###

# Next major
GET https://www.phraseexpress.com/update17.php?license=DEMO&hs=43f755f83538369dd7668077bee7448b HTTP/1.1

###

# To hit local instance of the Function
GET http://localhost:7071/api/GetLatestVersion HTTP/1.1
Connection : keep-alive

###

# To hit local instance of the Function w/ Beta option
GET http://localhost:7071/api/GetLatestVersion?beta=true HTTP/1.1
Connection : keep-alive
