name: Deploy PhraseExpress VersionFetcher

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'PhraseExpress/LatestVersionFunction/**'

permissions: 
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: 'PhraseExpressVersionChecker'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './PhraseExpress/LatestVersionFunction'

jobs:
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      with:
        show-progress: false

    - name: 'Build Function app'
      shell: pwsh # For Linux, use bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Publish to Azure'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}\output'